# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Symposium on Service-Oriented System Engineering (SOSE) 2018"
email: ""
description: "Renowned international conference on service-oriented system engineering."
baseurl: "/"
url: "http://uniba-dsg.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: ""
siteVerification: ""


# Organizer Info
organizerName: "University of Bamberg, DSG"
organizerAlternateName: "University of Bamberg, Distributed Systems Group"
organizerDescription: ""
organizerEmail: ""
organizerLogo: "/img/seo/ub-logo.png"
organizerLink: "https://www.uni-bamberg.de/en/pi/"

# Head
metaKeywords: "conference, event, ieee, soa, bamberg, symposium, computer, science, academia"
twitterAccount: "@"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# CFP Documents
submissionLink: ""
c4pUrl: "/blog/call-for-papers"
c4sponsorsUrl: ""


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "News"}
 - {permalink: "/blog/call-for-papers", text: "Call for Papers"}
# - {permalink: "/schedule/", text: "Program"}
# - {permalink: "/speakers/", text: "Keynotes"}
# - {permalink: "/team/", text: "Organizers"}
 - {permalink: "/logistics/", text: "Travel Info"}
# - {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 - {link: "", text: "Submit a paper"}
rightNavigationButtons:
 - {link: "", text: "Submit a paper"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "<typeout> 2018"
eventDate: "March 26 - 29, 2018"
typeoutTextValues: '"", "Service-Oriented System Engineering", "SOSE"'
typeoutFallback: "SOSE"
heroButtons:
# - {link: "/blog/call-for-papers", text: "Call for papers"}
# - {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "About SOSE"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "Starting from 2005, SOSE is one of the pioneering symposia devoted to the research in engineering service-oriented systems, from the architecture and computing paradigm to the development and management." }
 - {title: "Workshops", image: "workshop.jpg", text: "We are in the process of preparing several workshops for this years' conference. You can also submit proposals and ideas for workshops. See the <a href='/blog/call-for-papers'>Call for Papers</a> for more information." }
 - {title: "Events", image: "hackathon.jpg", text: "We are proud to announce that SOSE will be co-located with two other top conferences within the services and cloud computing field, <a href='http://big-dataservice.net/'>IEEE BigDataServices</a> and <a href='http://www.mobile-cloud.net/'>IEEE MobileCloud</a>." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "350", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure Google technologies"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
 - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Venue"
eventLocationName: "Welcome Congress Hotel Bamberg"
eventLocationLink: "https://www.welcome-hotels.com/en/welcome-kongresshotel-bamberg/info/"
eventStreetAddress: "Mußstr. 7"
eventAddressLocality: "Bamberg"
eventAddressLocalityRegion: "Bavaria"
eventPostalCode: "96047"
eventAddressCountry: "Germany"
eventStartTime: "2018-03-26T10:00"
eventDoorTime: "09:00"
eventEndTime: "2018-03-29T20:00"
eventPlaceCoordinates: "49.897300, 10.877420"
mapCenterCoordinates: "49.897300, 10.877420"
mapMobileCenterCoordinates: "49.897300, 10.877420"

# Venue Block
venueBlockTitle: "Location"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Bamberg, Germany"
venueFeatures: ["UNESCO World Heritage"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "sose2018"
twitterFeed: ""

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "http://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird"
  price: "350"
  priceCurrency: "UAH"
  ticketsNumber: "150"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-09-30T23:59"
 -
  name: "Last Chance"
  price: "450"
  priceCurrency: "UAH"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-10-01T00:00"
  validThrough: "2014-10-23T23:59"
  disabled: true
 -
  name: "Student"
  price: "200"
  priceCurrency: "UAH"
  ticketsNumber: "50"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"
  soldOut: true
  soldOutText: "Sold Out"

# Footer
socialLinks:
# - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=soseconference", icon: "twitter"}
# - {link: "https://facebook.com/GDGLviv", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://www.uni-bamberg.de/en/", text: "University of Bamberg"}
   - {link: "https://www.uni-bamberg.de/en/pi/", text: "Distributed Systems Group"}
 -
  title: "Contacts"
  links:
#   - {link: "mailto:guido.wirtz@uni-bamberg.de", text: "stefan.kolb@uni-bamberg.de"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: false
discusShortName: "sose2018"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.903256, 10.869848"
logisticsMapMobileCenterCoordinates: "49.903256, 10.869848"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Bamberg"
directionDetailsCards:
 - {title: "From the Airport", information: 'Bamberg is easily reachable by public transport, car or taxi from multiple airports within one to three hours. The closest airports are <a href="https://www.airport-nuernberg.de/english">Nuremberg Airport</a>, <a href="https://www.munich-airport.com/passengers-visitors-75328">Munich Airport</a> and <a href="https://www.frankfurt-airport.com/en/flights---more/flights.html">Frankfurt Airport</a>.'}
 - {title: "Public Transit", information: 'From the train station and within the city, it is easy to use public transport like <a href="http://www.vgn.de/CFF6B06F-C0B4-11D7-AE44-00034709FE0C">the bus</a> or a taxi. A lot of sites and locations are also in walking distance of the conference location and hotels.'}
 - {title: "Conference Hotel", information: 'The conference will take place at the <a href="https://www.welcome-hotels.com/en/welcome-kongresshotel-bamberg/info/">Welcome Congress Hotel Bamberg</a>. More information on conference rates and booking will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://www.bestwestern.com/en_US/book/hotel-details.95387.html", text: "Best Western Hotel"}
     - {link: "https://www.welcome-hotels.com/en/welcome-kongresshotel-bamberg/info/", text: "Welcome Kongresshotel"}
     - {link: "http://www.ibis.com/gb/hotel-8394-ibis-budget-bamberg/index.shtml", text: "Hotel ibis budget"}
 #  -
 #   title: "Registration"
 #   links:
 #    - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
 #    - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
 #    - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
 #    - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
 #  -
 #   title: "Attendance Details"
 #   links:
 #    - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
 #    - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
 #    - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
 #    - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: false

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
